### ISSUE TITLE
No release for darwin_arm64

### ISSUE THREAD

**Issue by jamescrowley** [orobix/terraform-provider-azureml#15]
When attempting to use this provider from a macOS (Apple Silicon), I get the following:
```

│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/telemaco019/azureml v0.0.1 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of
│ this provider may have different platforms supported.
```

Any chance of a compatible build? Many thanks!

**Comment by Telemaco019** [comment]
Definitely, I'll make a release with that build too in the next few days

**Comment by Telemaco019** [comment]
I'm closing the issue because I've made a release supporting darwin-arm64 as well. I also had to update the namespace of the provider from "telemaco019" to "orobix", so now you can install it as follows:
```
required_providers {
    azureml = {
      source  = "registry.terraform.io/orobix/azureml"
      version = "0.0.4"
    }
}
```
